dist: xenial
language: cpp
compiler: clang
addons:
	apt:
		packages:
		- libboost-test-dev
		- libspdlog-dev
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
	provider: script
	# Traivs, не удаляй файлы при деплое
	skip_cleanup: true
	script:
	- curl -f -T classwork01-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uifgeny87:$BINTRAY_API_KEY "https://api.bintray.com/content/ifgeny87/bt01-build-test-deploy/classwork/$TRAVIS_BUILD_NUMBER/classwork01-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_destribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
